[package]
name = "api-zhongli"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "1.0.0"
tokio = { version = "1", features = ["macros"] }
aws-config = "1.0"
aws-sdk-sts = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
