name = "api-zhongli"
main = "build/index.js"
compatibility_date = "2025-12-17"

[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release"

[[kv_namespaces]]
binding = "api-zhongli"
id = "api-zhongli"

[observability]
enabled = true